const PAIN_DRUG_REFERENCE = `
<section class="drug-reference">
<style>
.drug-reference{margin-top:16px}.drug-header{background:#eef6ff;border:1px solid #d7e8fb;border-radius:14px;padding:15px;margin-bottom:14px}.drug-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:15px;margin-bottom:12px}.drug-card summary{cursor:pointer;font-weight:700;color:#1e3a5f;font-size:14px}.drug-card h4{color:#1e3a5f;font-size:13px;margin:14px 0 6px}.drug-card p,.drug-card li{font-size:13px;line-height:1.6;color:#475569}.drug-card ul{padding-left:19px}.dose-box{background:#f8fafc;border-left:4px solid #4a90c2;padding:10px;border-radius:8px;margin:10px 0;font-size:12px}.warning{background:#fff7ed;border-left:4px solid #f59e0b;padding:10px 12px;border-radius:8px;font-size:12px;line-height:1.55;margin:10px 0}.pearl{background:#f8fafc;border-left:4px solid #4a90c2;padding:10px 12px;border-radius:8px;font-size:12px;margin-top:10px}.procedure-dose-grid{display:grid;gap:8px}.procedure-dose-grid>div{background:#f8fafc;border-radius:9px;padding:10px;font-size:12px;line-height:1.55;color:#475569}.reference-box{background:#f1f5f9;border-radius:12px;padding:12px;font-size:12px}.reference-box li{font-size:12px}
</style>
<div class="drug-header"><h3>💊 Drugs, Preparation & Safety</h3><p>Resident quick-reference for common drugs used in interventional pain procedures. Values below are <strong>educational examples, not universal prescriptions</strong>. Verify the exact product, route, patient factors and current hospital/specialty protocol before use.</p></div>
<div class="warning"><strong>Important:</strong> There is no single safe limit for every procedure. Local-anaesthetic limits depend on drug, total dose, patient weight and risk factors; steroid limits depend on product and procedure. Use the lowest effective dose and follow current guidance.</div>
<details class="drug-card" open><summary>1. Local anaesthetics</summary>
<h4>Lidocaine</h4><ul><li>1% = 10 mg/mL; 2% = 20 mg/mL.</li><li>Commonly used for skin infiltration and selected diagnostic blocks.</li><li><strong>Example dilution:</strong> 2% lidocaine 2 mL contains 40 mg. Add 2 mL compatible diluent to a total of 4 mL → 1% = 10 mg/mL.</li><li>Calculate total mg from skin infiltration plus procedural injectate. Do not rely on mL alone.</li></ul>
<h4>Bupivacaine</h4><ul><li>0.25% = 2.5 mg/mL; 0.5% = 5 mg/mL.</li><li>Longer-acting local anaesthetic; use the minimum effective dose because serious cardiotoxicity can occur.</li></ul>
<h4>Ropivacaine</h4><ul><li>0.2% = 2 mg/mL; 0.5% = 5 mg/mL.</li><li>Longer-acting option; LAST remains possible.</li></ul>
<div class="dose-box"><strong>Concentration formula:</strong> % × 10 = mg/mL. Example: 0.25% bupivacaine = 2.5 mg/mL; 4 mL = 10 mg.</div>
<h4>Safety</h4><ul><li>Calculate total dose before injection.</li><li>Inject incrementally with appropriate aspiration/checks.</li><li>Have a current LAST checklist and lipid-emulsion rescue plan available when clinically indicated.</li><li>Reduce exposure in frail/elderly patients and those with factors increasing systemic toxicity.</li></ul></details>
<details class="drug-card"><summary>2. Corticosteroids</summary>
<h4>Dexamethasone</h4><ul><li>Common products include 4 mg/mL or 10 mg/mL; verify the actual vial.</li><li>Example: 4 mg/mL × 1 mL = 4 mg.</li><li>Non-particulate dexamethasone is commonly considered when an epidural steroid is indicated, especially where embolic risk is a concern.</li></ul>
<h4>Triamcinolone / methylprednisolone</h4><ul><li>Common depot products may be 40 mg/mL, but concentration varies by manufacturer.</li><li>These are particulate steroids. Their use, especially for transforaminal epidural injection, requires careful adherence to current specialty guidance.</li><li>Higher steroid dose does not automatically mean better analgesia; current multisociety guidance supports using the lowest effective dose for musculoskeletal injections.</li></ul>
<div class="warning"><strong>Epidural warning:</strong> Epidural corticosteroid administration is not FDA-approved and rare serious neurological adverse events have been reported. Do not use a generic “steroid cocktail” or generic maximum dose; follow the exact approach-specific protocol.</div>
<h4>Other safety points</h4><ul><li>Consider diabetes/transient hyperglycaemia, infection risk, immunosuppression, osteoporosis and cumulative exposure.</li><li>Confirm exact vial, concentration, particulate status, preservative status and intended route before drawing up.</li></ul></details>
<details class="drug-card"><summary>3. Contrast media</summary><ul><li>Non-ionic iodinated contrast is commonly used for fluoroscopy-guided procedures when contrast is indicated.</li><li>Use the smallest amount needed to confirm target/spread.</li><li>Review prior contrast reactions, renal function and other patient-specific risks according to local policy.</li></ul></details>
<details class="drug-card"><summary>4. Saline / diluent</summary><ul><li>0.9% sodium chloride may be used when compatible with the selected medication and route.</li><li>Use sterile single-use preparations and aseptic technique.</li><li>Do not dilute merely to increase volume; preserve the intended final concentration and total dose.</li></ul></details>
<details class="drug-card"><summary>5. Procedure-specific practical preparation</summary><div class="procedure-dose-grid">
<div><strong>Medial branch block:</strong> small-volume local anaesthetic is generally used for a diagnostic block. Exact volume/concentration should follow the service protocol; excessive volume can reduce diagnostic specificity.</div>
<div><strong>Facet injection:</strong> local anaesthetic ± corticosteroid may be used depending on diagnostic/therapeutic purpose and current evidence. Prepare only after confirming the intended purpose.</div>
<div><strong>SI joint injection:</strong> local anaesthetic ± corticosteroid may be used. Use image guidance and the lowest effective volume consistent with the target.</div>
<div><strong>Genicular block:</strong> small-volume local anaesthetic around each intended sensory target; remember accompanying genicular vessels.</div>
<div><strong>Stellate ganglion block:</strong> low-volume, carefully targeted local anaesthetic under image guidance. Nearby airway and vascular structures make volume and needle position particularly important.</div>
<div><strong>Epidural steroid injection:</strong> drug choice and steroid dose depend on approach and current guidance. Avoid generic mixtures; use the exact approach-specific protocol.</div>
</div></details>
<details class="drug-card"><summary>6. LAST — minimum emergency knowledge</summary><p>Early toxicity can include circumoral numbness, tinnitus, metallic taste, agitation or altered mental status; severe toxicity can cause seizures, arrhythmias and cardiovascular collapse.</p><ul><li><strong>Stop injecting</strong> and call for help.</li><li>Prioritize airway/oxygenation and manage seizures/cardiovascular instability according to the current LAST checklist.</li><li>Keep lipid emulsion and the institutional LAST protocol immediately accessible where significant local-anaesthetic dosing is performed.</li></ul><div class="pearl"><strong>Resident pearl:</strong> Know the total milligrams before injecting. “mL” is not a dose.</div></details>
<div class="reference-box"><strong>References to verify before clinical use</strong><ul><li>ASRA Pain Medicine LAST guidance/checklist.</li><li>ASRA Pain Medicine anticoagulation guidance.</li><li>ASRA multisociety corticosteroid injection guidance.</li><li>Current manufacturer prescribing information for the exact product stocked by your hospital.</li></ul></div>
</section>
`;
