/* PainMed Pro — local Notes/PDF + Flashcards/Image manager */
(function(){
const DB='painmed-media-v1',STORE='items';let db;
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(mode){return db.transaction(STORE,mode).objectStore(STORE)}
function all(){return new Promise((res,rej)=>{const r=tx('readonly').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function add(item){return new Promise((res,rej)=>{const r=tx('readwrite').add(item);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function remove(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(Number(id));r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const byId=id=>document.getElementById(id);
function openModal(type){const isNote=type==='note',modal=document.createElement('div');modal.className='media-modal';modal.id='media-modal';modal.innerHTML=`<div class="media-sheet"><h2>${isNote?'📝 Add Note + PDF':'🃏 Add Flashcard + Image'}</h2><div class="media-field"><label>Title / Question</label><input id="media-title-input" placeholder="${isNote?'e.g. Lumbar radiculopathy':'e.g. Identify this image'}"></div><div class="media-field"><label>${isNote?'Note text':'Answer / Explanation'}</label><textarea id="media-text-input" placeholder="Enter your content..."></textarea></div><div class="media-field"><label>${isNote?'PDF file':'Image file'}</label><input class="media-file" id="media-file-input" type="file" accept="${isNote?'application/pdf,.pdf':'image/*'}"></div><div id="media-file-preview"></div><div class="media-note">Files are stored locally on this device/browser using IndexedDB. They are not uploaded to a server.</div><div class="media-row"><button class="media-btn" onclick="window.closeMediaModal()" style="background:#e2e8f0;color:#1e293b">Cancel</button><button class="media-btn" id="media-save-btn">Save</button></div></div>`;document.body.appendChild(modal);
byId('media-file-input').onchange=e=>{const f=e.target.files[0],p=byId('media-file-preview');if(!f){p.innerHTML='';return}if(isNote)p.innerHTML=`<div class="media-note">📄 ${esc(f.name)} (${Math.round(f.size/1024)} KB)</div>`;else{const u=URL.createObjectURL(f);p.innerHTML=`<img class="media-preview" src="${u}" alt="Preview">`}};
byId('media-save-btn').onclick=async()=>{const title=byId('media-title-input').value.trim(),text=byId('media-text-input').value.trim(),file=byId('media-file-input').files[0];if(!title){alert('Please enter a title/question.');return}if(!file){alert(`Please select a ${isNote?'PDF':'image'}.`);return}if(isNote&&!file.name.toLowerCase().endsWith('.pdf')){alert('Please select a PDF file.');return}await add({type,title,text,fileName:file.name,mime:file.type,blob:file,created:Date.now()});closeMediaModal();render(type)} }
function closeMediaModal(){const m=byId('media-modal');if(m)m.remove()}window.closeMediaModal=closeMediaModal;
async function render(type){const root=byId(type==='note'?'notes-list':'flashcards-list');if(!root)return;const items=(await all()).filter(x=>x.type===type).sort((a,b)=>b.created-a.created);if(!items.length){root.innerHTML=`<div class="media-empty">${type==='note'?'No notes yet. Add a note and attach a PDF.':'No flashcards yet. Add an image-based flashcard.'}</div>`;return}root.innerHTML='';for(const item of items){const u=URL.createObjectURL(item.blob),card=document.createElement('div');if(type==='note'){card.className='media-card';card.innerHTML=`<h3>${esc(item.title)}</h3><p>${esc(item.text).replace(/\n/g,'<br>')}</p><div class="media-actions"><button class="media-link" onclick="window.openMediaPdf(${item.id})">📄 Open PDF</button><button class="media-delete" onclick="window.deleteMedia(${item.id},'note')">Delete</button></div>`}else{card.className='media-card flash-card';card.innerHTML=`<div class="flash-inner"><div class="flash-face"><div class="flash-label">Question</div><h3>${esc(item.title)}</h3><img class="flash-image" src="${u}" alt="Flashcard image"><p>Tap card to reveal answer</p></div><div class="flash-face flash-back"><div class="flash-label">Answer</div><p>${esc(item.text).replace(/\n/g,'<br>')}</p><img class="flash-image" src="${u}" alt="Flashcard image"></div></div><div class="media-actions"><button class="media-delete" onclick="event.stopPropagation();window.deleteMedia(${item.id},'flash')">Delete</button></div>`;card.onclick=()=>card.classList.toggle('flipped')}root.appendChild(card)}}
window.openMediaPdf=async id=>{const item=(await all()).find(x=>x.id===id);if(!item)return;const u=URL.createObjectURL(item.blob),modal=document.createElement('div');modal.className='media-modal';modal.id='media-modal';modal.innerHTML=`<div class="media-sheet"><h2>📄 ${esc(item.title)}</h2><iframe class="pdf-preview" src="${u}"></iframe><div class="media-actions"><a class="media-link" href="${u}" target="_blank">Open full screen</a><button class="media-btn" onclick="window.closeMediaModal()">Close</button></div></div>`;document.body.appendChild(modal)};
window.deleteMedia=async(id,type)=>{if(!confirm('Delete this item?'))return;await remove(id);render(type)};
function addViews(){const main=document.querySelector('.content');if(!main)return;if(!byId('view-notes'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-notes"><div class="media-view"><div class="media-head"><div><div class="media-title">My Notes</div><div class="media-subtitle">Personal notes with attached PDFs</div></div><button class="media-btn" onclick="window.openMediaForm('note')">＋ Add Note</button></div><div id="notes-list"></div></div></section>`);if(!byId('view-flashcards'))main.insertAdjacentHTML('beforeend',`<section class="view" id="view-flashcards"><div class="media-view"><div class="media-head"><div><div class="media-title">Flashcards</div><div class="media-subtitle">Image-based recall cards</div></div><button class="media-btn" onclick="window.openMediaForm('flash')">＋ Add Card</button></div><div id="flashcards-list"></div></div></section>`);window.openMediaForm=openModal;document.querySelectorAll('.action-card').forEach(c=>{const t=c.querySelector('.title')?.textContent;if(t==='My Notes')c.onclick=()=>{navigateTo('notes');render('note')};if(t==='Flashcards')c.onclick=()=>{navigateTo('flashcards');render('flash')}})}
function start(){openDB().then(()=>{addViews();render('note');render('flash')}).catch(()=>alert('Local storage is unavailable.'))}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();})();
