// ============================================
// PAINMED PRO — JAVASCRIPT
// OPD Pain Medicine Study Tracker
// ============================================

const weeksData = [
  {week:1,phase:'Phase 1',phaseClass:'phase-1',dates:'Aug 10 – Aug 16',title:'OPD Pain Assessment Framework',desc:'Master SOCRATES/OPQRST frameworks • Red flag screening • Pain scales (VAS, NPRS, McGill) • Build a 15-minute assessment template',daily:['Mon: Read pain assessment frameworks (SOCRATES, OPQRST)','Tue: Watch physical exam videos for common presentations','Wed: Practice: Write 3 mock pain histories','Thu: Study red flags in chronic pain — memorize the list','Fri: Review pain scales — when to use each','Sat: Self-Assessment: Timed 15-min mock patient assessment','Sun: Reflection & note template creation'],tags:['🎯 15-min assessment','🚩 10+ red flags','📝 Note template']},
  {week:2,phase:'Phase 1',phaseClass:'phase-1',dates:'Aug 17 – Aug 23',title:'Pain Mechanisms & Classification',desc:'Nociceptive vs neuropathic vs nociplastic pain • Central sensitization • Biopsychosocial model • ICD-11 chronic pain codes',daily:[],tags:['🧠 Mechanisms','📋 ICD-11 Codes']},
  {week:3,phase:'Phase 1',phaseClass:'phase-1',dates:'Aug 24 – Aug 30',title:'OPD Investigations & Imaging',desc:'When to order MRI/CT/EMG/NCV/bone scan • Imaging-pain correlation • Lab workup for inflammatory/rheumatologic pain • Avoiding over-investigation',daily:[],tags:[]},
  {week:4,phase:'Phase 2',phaseClass:'phase-2',dates:'Aug 31 – Sep 06',title:'Musculoskeletal Pain',desc:'Mechanical low back & neck pain • Osteoarthritis (knee, hip, spine) • Myofascial pain syndrome & trigger points • Tendinopathies & bursitis • Exercise prescription basics',daily:[],tags:[]},
  {week:5,phase:'Phase 2',phaseClass:'phase-2',dates:'Sep 07 – Sep 13',title:'Neuropathic Pain',desc:'Diabetic neuropathy • Post-herpetic neuralgia • Radiculopathy & sciatica • Trigeminal neuralgia • Screening tools: DN4, LANSS, painDETECT',daily:[],tags:[]},
  {week:6,phase:'Phase 2',phaseClass:'phase-2',dates:'Sep 14 – Sep 20',title:'Headache & Facial Pain',desc:'Tension-type, migraine, cluster headaches • Medication overuse headache • Temporomandibular disorders • Atypical facial pain',daily:[],tags:[]},
  {week:7,phase:'Phase 2',phaseClass:'phase-2',dates:'Sep 21 – Sep 27',title:'Complex & Functional Pain',desc:'Fibromyalgia & chronic fatigue • Chronic primary pain • Chronic pelvic pain & endometriosis • CRPS — early recognition • Activity pacing strategies',daily:[],tags:[]},
  {week:8,phase:'Phase 2',phaseClass:'phase-2',dates:'Sep 28 – Oct 04',title:'Cancer Pain in OPD',desc:'WHO analgesic ladder • Breakthrough pain management • Opioid rotation principles • Adjuvant analgesics in cancer • Palliative care referral criteria',daily:[],tags:[]},
  {week:9,phase:'Phase 3',phaseClass:'phase-3',dates:'Oct 05 – Oct 11',title:'Non-Opioid Analgesics',desc:'Paracetamol dosing & hepatotoxicity • NSAID selection • GI/renal/cardiac risk stratification • Topical agents • Perioperative NSAID holds',daily:[],tags:[]},
  {week:10,phase:'Phase 3',phaseClass:'phase-3',dates:'Oct 12 – Oct 18',title:'Opioids in OPD',desc:'Morphine, oxycodone, tramadol, buprenorphine, fentanyl patches • Equianalgesic dosing • Risk assessment • Urine screening • Tapering protocols • OIH',daily:[],tags:[]},
  {week:11,phase:'Phase 3',phaseClass:'phase-3',dates:'Oct 19 – Oct 25',title:'Adjuvant Analgesics',desc:'TCAs • SNRIs • Gabapentinoids • Muscle relaxants • Low-dose ketamine • Corticosteroids in pain management',daily:[],tags:[]},
  {week:12,phase:'Phase 3',phaseClass:'phase-3',dates:'Oct 26 – Nov 01',title:'Special Populations',desc:'Geriatrics • Pregnancy & lactation • Pediatric pain • Renal & hepatic impairment dose adjustments',daily:[],tags:[]},
  {week:13,phase:'Phase 4',phaseClass:'phase-4',dates:'Nov 02 – Nov 08',title:'Physical Therapy & Psychology',desc:'Exercise prescription • CBT & ACT basics • TENS • Sleep hygiene & pain relationship • Referral criteria',daily:[],tags:[]},
  {week:14,phase:'Phase 4',phaseClass:'phase-4',dates:'Nov 09 – Nov 15',title:'OPD Interventional Procedures',desc:'Trigger point injections • Joint injections • Bursa/tendon sheath injections • Basic nerve blocks • Scope & referral',daily:[],tags:[]},
  {week:15,phase:'Phase 4',phaseClass:'phase-4',dates:'Nov 16 – Nov 22',title:'Documentation & Legal',desc:'Opioid agreements • Pain clinic SOAP note • Disability certification • Informed consent • Telemedicine limitations',daily:[],tags:[]},
  {week:16,phase:'Phase 4',phaseClass:'phase-4',dates:'Nov 23 – Nov 29',title:'Complex Cases & Referral',desc:'Failed back surgery syndrome • Opioid use disorder • Spinal cord stimulation & intrathecal pumps • Multidisciplinary pain programs • Board prep',daily:[],tags:[],isLast:true}
];

function navigateTo(viewName){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+viewName).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));const nav=document.querySelector('.nav-item[data-view="'+viewName+'"]');if(nav)nav.classList.add('active');if(viewName==='dashboard')updateDashboard();if(viewName==='theory')loadTheory();}
function showToast(message){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500);}
function saveProgress(){const checked=[];for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);if(cb&&cb.checked)checked.push(i);}localStorage.setItem('painmed_progress',JSON.stringify(checked));}
function loadProgress(){try{const saved=JSON.parse(localStorage.getItem('painmed_progress')||'[]');saved.forEach(week=>{const cb=document.getElementById('chk-'+week);if(cb)cb.checked=true;});}catch(e){}}
function resetProgress(){if(confirm('Reset all progress? This cannot be undone.')){for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);if(cb)cb.checked=false;}localStorage.removeItem('painmed_progress');updateProgress();updateDashboard();showToast('Progress reset successfully');}}
function updateProgress(){let checked=0;for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);if(cb&&cb.checked)checked++;}saveProgress();updateDashboard();updateCurrentWeek();for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);const header=document.querySelector('#week-card-'+i+' .week-header');const title=document.querySelector('#week-card-'+i+' .week-title');if(header)header.classList.toggle('done',!!cb&&cb.checked);if(title)title.classList.toggle('done',!!cb&&cb.checked);}}
function updateDashboard(){let checked=0;for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);if(cb&&cb.checked)checked++;}const percent=Math.round((checked/16)*100);const ids=[['hero-percent',percent+'%'],['hero-done',checked],['hero-left',16-checked],['hero-ring',percent+'%']];ids.forEach(([id,val])=>{const el=document.getElementById(id);if(el)el.textContent=val;});}
function updateCurrentWeek(){let currentWeek=1;for(let i=1;i<=16;i++){const cb=document.getElementById('chk-'+i);if(!cb||!cb.checked){currentWeek=i;break;}currentWeek=16;}const w=weeksData[currentWeek-1];['current-badge','current-title','current-desc'].forEach(()=>{});const b=document.getElementById('current-badge'),t=document.getElementById('current-title'),d=document.getElementById('current-desc');if(b)b.textContent='WEEK '+w.week;if(t)t.textContent=w.title;if(d)d.textContent=w.desc;}
function renderRoster(){const container=document.getElementById('weeks-container');if(!container)return;container.innerHTML=weeksData.map(w=>`<div class="week-card" data-phase="${w.phase}" id="week-card-${w.week}"><div class="week-header ${w.phaseClass}" onclick="toggleWeek(${w.week})"><div class="checkbox-wrap" onclick="event.stopPropagation()"><input type="checkbox" id="chk-${w.week}" onchange="updateProgress()"><div class="check-visual">✓</div></div><div class="week-meta"><div class="week-badges"><span class="badge-week">WEEK ${w.week}</span><span class="badge-date">${w.dates}</span></div><h3 class="week-title">${w.title}</h3></div><span class="arrow" id="arrow-${w.week}">▼</span></div><div class="week-content" id="content-${w.week}"><p><strong>Key Deliverables:</strong> ${w.desc}</p>${w.daily.length?`<div class="daily-plan"><div class="daily-plan-title">📚 Daily Plan (~5 hrs total)</div><ul>${w.daily.map(d=>`<li>${d}</li>`).join('')}</ul></div>`:''}${w.tags.length?`<div class="tags">${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`:''}${w.isLast?`<div class="completion-banner"><p>🎓 Congratulations! You have completed the 16-week OPD Pain Medicine course.</p></div>`:''}</div></div>`).join('');}
function toggleWeek(weekNum){const c=document.getElementById('content-'+weekNum),a=document.getElementById('arrow-'+weekNum);if(c)c.classList.toggle('open');if(a)a.classList.toggle('open');}
function filterPhase(phase){document.querySelectorAll('.phase-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.phase===phase));document.querySelectorAll('.week-card').forEach(card=>card.style.display=(phase==='all'||card.dataset.phase===phase)?'block':'none');}

// ============================================
// PAIN PROCEDURE REFERENCE FALLBACK
// The complete reference is also in procedure-reference.js.
// This built-in version guarantees the new sections appear
// even if a static-host/CDN request to that file is delayed.
// ============================================
function builtInProcedureReference(){return `
<style>
.pr-wrap{margin-top:14px}.pr-card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:14px;margin:0 0 12px}.pr-card summary{cursor:pointer;font-weight:700;color:#1e3a5f;font-size:14px}.pr-card h4{margin:13px 0 6px;color:#1e3a5f;font-size:13px}.pr-card p,.pr-card li{font-size:12.5px;line-height:1.6;color:#475569}.pr-card ul{padding-left:18px}.pr-note{background:#eef6ff;border-left:4px solid #4a90c2;padding:10px;border-radius:8px;font-size:12px;line-height:1.55;margin:10px 0}.pr-warn{background:#fff7ed;border-left:4px solid #f59e0b;padding:10px;border-radius:8px;font-size:12px;line-height:1.55;margin:10px 0}.pr-danger{background:#fef2f2;border-left:4px solid #dc2626;padding:10px;border-radius:8px;font-size:12px;line-height:1.55;margin:10px 0}.pr-grid{display:grid;grid-template-columns:1fr;gap:8px}.pr-box{background:#f8fafc;border-radius:9px;padding:10px}.pr-table{width:100%;border-collapse:collapse;font-size:11px}.pr-table th,.pr-table td{padding:7px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}.pr-table th{color:#1e3a5f}.calc{background:#f8fafc;border:1px solid #dbe5ef;border-radius:12px;padding:12px}.calc label{display:block;font-size:11px;color:#475569;margin:7px 0 3px}.calc input,.calc select{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.calc button{margin-top:9px;padding:9px 12px;border:0;border-radius:8px;background:#1e3a5f;color:#fff;font-weight:700}.calc-result{margin-top:10px;padding:10px;border-radius:8px;background:#fff;border:1px solid #dbe5ef;font-size:12px}
</style>
<div class="pr-wrap">
<div class="pr-card"><details open><summary>🛡️ Before You Inject — Universal Checklist</summary><ul><li>Confirm patient, procedure, side/site and indication.</li><li>Review imaging and relevant anatomy.</li><li>Consent: expected benefit, alternatives and important complications.</li><li>Check allergy, infection, anticoagulant/antiplatelet therapy and relevant comorbidities.</li><li>Confirm local anaesthetic concentration, total dose and steroid/contrast choice.</li><li>Use appropriate monitoring and ensure airway/resuscitation equipment is available.</li><li>Have a LAST rescue pathway available when significant local-anaesthetic exposure is possible.</li><li>Document baseline neurological findings and perform a timeout.</li></ul><div class="pr-note"><strong>Safety:</strong> Use current specialty guidance and your local hospital protocol. This section is an educational reference, not a substitute for supervision or local policy.</div></details></div>
<div class="pr-card"><details open><summary>🧮 Local Anaesthetic Dose Calculator</summary><div class="calc"><label>Patient weight (kg)</label><input id="pr-weight" type="number" min="1" step="0.1" placeholder="e.g. 70"><label>Local anaesthetic</label><select id="pr-la"><option>Lidocaine</option><option>Lidocaine + epinephrine</option><option>Bupivacaine</option><option>Ropivacaine</option></select><label>Concentration (%)</label><input id="pr-conc" type="number" min="0.01" step="0.01" placeholder="e.g. 0.25"><label>Volume (mL)</label><input id="pr-vol" type="number" min="0" step="0.1" placeholder="e.g. 4"><button type="button" onclick="calculatePainDose()">Calculate</button><div id="pr-dose-result" class="calc-result">Enter values to calculate total mg and mg/kg.</div></div><div class="pr-warn"><strong>Important:</strong> This calculates administered dose; it does not declare a dose safe. Maximum-dose limits vary by product, route, patient factors and institutional policy. Verify the exact product label and local protocol.</div></details></div>
<div class="pr-card"><details open><summary>💉 Procedure Drug Quick Reference</summary><table class="pr-table"><tr><th>Procedure</th><th>Drug concept</th><th>Safety focus</th></tr><tr><td>Lumbar MBB</td><td>Small-volume local anaesthetic for diagnostic block; steroid is not automatically required.</td><td>Keep volume appropriate to diagnostic specificity.</td></tr><tr><td>Facet joint injection</td><td>Local anaesthetic ± corticosteroid according to indication.</td><td>Confirm target and use the lowest effective steroid exposure.</td></tr><tr><td>SI joint</td><td>Local anaesthetic ± corticosteroid.</td><td>Image guidance and controlled volume.</td></tr><tr><td>Genicular block</td><td>Small-volume local anaesthetic around selected sensory targets.</td><td>Genicular vessels may accompany nerves.</td></tr><tr><td>Genicular RFA</td><td>Diagnostic-block pathway followed by radiofrequency treatment.</td><td>Accurate bony target and electrode position.</td></tr><tr><td>Stellate ganglion</td><td>Low-volume local anaesthetic under image guidance.</td><td>Close to carotid/vertebral vessels and airway structures.</td></tr><tr><td>Epidural steroid</td><td>Steroid choice depends on approach; non-particulate steroid is commonly favored in higher-risk transforaminal contexts.</td><td>Follow current approach-specific guidance.</td></tr><tr><td>Celiac plexus</td><td>Local anaesthetic for diagnostic block; neurolysis is a separate specialist intervention.</td><td>Major vascular/visceral structures require careful image guidance.</td></tr><tr><td>Ganglion impar</td><td>Local anaesthetic ± steroid for selected blocks.</td><td>Confirm presacral target and avoid rectal/vascular injury.</td></tr></table></details></div>
<div class="pr-card"><details open><summary>🦴 Anatomy Checklist</summary><div class="pr-grid"><div class="pr-box"><strong>Lumbar MBB/RFA:</strong> transverse process • superior articular process • medial branch course • mammillo-accessory region.</div><div class="pr-box"><strong>SI joint:</strong> sacral ala • posterior SI joint • sacral foramina • iliac surface.</div><div class="pr-box"><strong>Genicular:</strong> femoral/tibial epicondylar regions • genicular vessels • collateral ligaments • target nerve regions.</div><div class="pr-box"><strong>Stellate ganglion:</strong> longus colli • carotid sheath • thyroid • prevertebral fascia • vertebral artery region.</div><div class="pr-box"><strong>Celiac plexus:</strong> aorta • celiac trunk • diaphragmatic crura • vertebral body • plexus region.</div><div class="pr-box"><strong>Ganglion impar:</strong> coccyx • sacrococcygeal junction • presacral space • rectum.</div></div></details></div>
<div class="pr-card"><details open><summary>⚠️ Complications & Immediate Response</summary><div class="pr-grid"><div class="pr-box"><strong>Vasovagal:</strong> stop procedure, assess ABCs, position appropriately, monitor and treat per local protocol.</div><div class="pr-box"><strong>Intravascular injection:</strong> stop injection immediately and assess neurological/cardiovascular status.</div><div class="pr-box"><strong>LAST:</strong> stop local anaesthetic, call for help, manage airway/oxygenation and seizures, and follow the current ASRA lipid-emulsion algorithm.</div><div class="pr-box"><strong>Epidural haematoma:</strong> new severe back pain, weakness, sensory or bladder/bowel change requires urgent neurological assessment and imaging.</div><div class="pr-box"><strong>Infection:</strong> do not inject through infected tissue; investigate fever/systemic or neurological symptoms promptly.</div><div class="pr-box"><strong>Pneumothorax:</strong> consider after procedures near pleura; assess symptoms and oxygenation and obtain urgent imaging when indicated.</div></div></details></div>
<div class="pr-card"><details open><summary>🚑 LAST Quick Rescue Reference</summary><div class="pr-danger"><strong>Use the current ASRA LAST checklist at the bedside.</strong> The ASRA checklist describes 20% lipid emulsion with weight-based bolus/infusion dosing and a maximum lipid dose of 12 mL/kg. Follow the current checklist rather than relying on memory.</div><ul><li>Call for help and obtain the LAST rescue kit.</li><li>Ensure airway/oxygenation and manage seizures, preferably with benzodiazepines.</li><li>Follow the ASRA modified resuscitation approach.</li><li>Avoid additional local anaesthetic and the medications specifically discouraged in the current ASRA LAST checklist.</li></ul><p><a href="https://asra.com/docs/default-source/guidelines-articles/local-anesthetic-systemic-toxicity-rgb.pdf" target="_blank" rel="noopener noreferrer">Open ASRA LAST checklist ↗</a></p></details></div>
<div class="pr-card"><details open><summary>📝 Documentation Template</summary><ul><li>Indication/diagnosis and consent.</li><li>Allergy, infection and anticoagulation review.</li><li>Procedure, side, level and imaging modality.</li><li>Needle/device and target.</li><li>Contrast and observed spread where applicable.</li><li>Drug name, concentration, volume and total mg.</li><li>Steroid name and dose if used.</li><li>Immediate complications and neurological status.</li><li>Post-procedure instructions, red flags and follow-up.</li></ul></details></div>
<div class="pr-card"><details open><summary>⭐ Exam Pearls</summary><ul><li><strong>MBB ≠ facet injection:</strong> different diagnostic/therapeutic questions.</li><li><strong>RFA requires patient selection:</strong> it is not a generic treatment for nonspecific pain.</li><li><strong>Volume matters:</strong> excessive local anaesthetic volume can reduce diagnostic specificity.</li><li><strong>mL ≠ dose:</strong> convert concentration to mg/mL and calculate total mg.</li><li><strong>Particulate vs non-particulate steroid:</strong> selection is especially important for transforaminal epidural procedures.</li><li><strong>Anticoagulation is procedure-specific:</strong> use current ASRA pain-procedure guidance.</li></ul></details></div>
<div class="pr-card"><details open><summary>📚 Guideline & Update Sources</summary><ul><li><a href="https://asra.com/guidelines-articles" target="_blank" rel="noopener noreferrer">ASRA Pain Medicine Guidelines & Articles ↗</a></li><li><a href="https://asra.com/news-publications/asra-updates/blog-landing/guidelines/2022/12/14/interventional-spine-and-pain-procedures-in-patients-on-antiplatelet-and-anticoagulant-medications-%28second-edition%29" target="_blank" rel="noopener noreferrer">ASRA Anticoagulation Guidance ↗</a></li><li><a href="https://asra.com/news-publications/asra-updates/blog-landing/guidelines/2020/11/01/checklist-for-treatment-of-local-anesthetic-systemic-toxicity" target="_blank" rel="noopener noreferrer">ASRA LAST Guidance ↗</a></li></ul><div class="pr-note"><strong>Last reviewed:</strong> August 2026. Verify current source and local hospital protocol before clinical use.</div></details></div>
</div>`;}

function calculatePainDose(){const w=parseFloat(document.getElementById('pr-weight')?.value);const c=parseFloat(document.getElementById('pr-conc')?.value);const v=parseFloat(document.getElementById('pr-vol')?.value);const out=document.getElementById('pr-dose-result');if(!out)return;if(!w||!c||!v||w<=0||c<=0||v<0){out.textContent='Enter a valid weight, concentration and volume.';return;}const mgml=c*10,total=mgml*v,mgkg=total/w;out.innerHTML='<strong>'+mgml.toFixed(2)+' mg/mL</strong><br>Total dose: <strong>'+total.toFixed(2)+' mg</strong><br>Dose: <strong>'+mgkg.toFixed(2)+' mg/kg</strong><br><small>Verify this result against the exact product label and institutional maximum-dose policy.</small>';}

// ============================================
// THEORY LOADER
// ============================================
let latestTheory=null;
async function loadTheory(){
  const target=document.getElementById('theory-content');
  if(!target)return;
  target.innerHTML='<div style="padding:20px;text-align:center;color:#64748b">Loading updated theory…</div>';
  try{
    const version=Date.now();
    const theoryResponse=await fetch('./theory-data.js?v='+version,{cache:'no-store'});
    if(!theoryResponse.ok)throw new Error('Theory file could not be loaded');
    const theorySource=await theoryResponse.text();
    latestTheory=new Function(theorySource+'\n;return THEORY;')();
    if(!latestTheory||!latestTheory.length)throw new Error('Theory data is empty');

    let reference='';
    try{
      const refResponse=await fetch('./procedure-reference.js?v='+version,{cache:'no-store'});
      if(refResponse.ok){
        const refSource=await refResponse.text();
        reference=new Function(refSource+'\n;return PROCEDURE_REFERENCE;')();
      }
    }catch(e){console.warn('Procedure reference request failed; using built-in reference.',e);}

    // IMPORTANT: always show the new reference. This fixes hosts/CDNs that fail to fetch the secondary JS file.
    if(!reference)reference=builtInProcedureReference();
    target.innerHTML=latestTheory[0].content+reference;
  }catch(error){
    console.error('Theory update failed:',error);
    if(typeof THEORY!=='undefined'&&THEORY.length){target.innerHTML=THEORY[0].content+builtInProcedureReference();}
    else target.innerHTML='<div style="padding:20px">Unable to load Theory. Please reconnect and reopen the Theory tab.</div>';
  }
}

document.addEventListener('DOMContentLoaded',function(){renderRoster();loadProgress();updateProgress();updateCurrentWeek();});
